violation_checker_job:
  every:
    - "20m"
    - :first_in: "1m"
  class: "ViolationCheckerJob"
  queue: simple
  description: "Runs violations checks for workers"

managers_notifier_job:
  cron: '0 9 * * *'
  class: 'ManagerNotifierJob'
  queue: simple
  descripton: 'Runs notifiers for managers'
